#!/usr/bin/env python3
"""HomeIsland command line interface. See `homeisland --help`."""

import os
import sys

if sys.version_info < (3, 9):
    sys.exit("homeisland requires Python 3.9 or newer")

sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), "lib"))

from homeisland.cli import main  # noqa: E402

if __name__ == "__main__":
    sys.exit(main())
